### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by hynra** [fweinaug/expandable_text#2]
Any plan to support web platform?

**Comment by fweinaug** [comment]
I just tried to add web support but unfortunately it does not work yet due to this [Flutter issue](https://github.com/flutter/flutter/issues/65940). As soon as the issue is resolved I'll release it.

**Comment by fweinaug** [comment]
almost 1.5 years later and the [Flutter issue](https://github.com/flutter/flutter/issues/65940) is still not resolved.

**Comment by timobaehr** [comment]
Using this inside Flutter Web project. Is working fine. I think this issue can be closed.

You can try out here: https://app.ehwplus.com/#/features
After two lines magic begins to happen.

**Comment by ChamikaAshen** [comment]
Still not working on Flutter HTML renderer. Text presents just expanded without any button

**Comment by jamiejacksoncumbria** [comment]
Still not working on Flutter HTML renderer. Text presents just expanded without any button.

Any Solution to the this yet. I have the same issue?
